on:
  workflow_dispatch:

name: Development Build and Deploy

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Fetch LFS objects
        run: git lfs checkout

      - name: Create env file
        run: |
          touch .env

      - name: Build Project
        run: |
          yarn
          yarn build

      - name: Upload files
        uses: easingthemes/ssh-deploy@main
        env:
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          TARGET: "/domains/jakubkaras.pl/public_html/landing-dev"
